Repository hanfei1991/microcosm, pull requests merged in 2022-05, with the labels that each got.

#354 feat(orm): add more function to support framework client(part II)
  go.mod
  go.sum
  lib/model/master.go
  lib/model/status.go
  pkg/errors/errors.go
  pkg/externalresource/resourcemeta/model.go
  pkg/orm/client.go
  pkg/orm/client_test.go
  pkg/orm/config.go
  pkg/orm/mock.go
  pkg/orm/mock_test.go
  pkg/orm/model/common.go
  pkg/orm/model/logic_epoch.go
  pkg/orm/model/logic_epoch_test.go
  pkg/orm/model/project.go
  pkg/orm/util.go
  pkg/tenant/tenant.go
Labels: status/ptal

#360 executor: retry register when meeting MasterNotReady error
  executor/server.go
  executor/server_test.go
Labels: status/ptal

#363 update ansible readme
  ansible/README.md
Labels: status/ptal

#355 ci: add node failure test
  lib/fake/fake_master.go
  lib/fake/fake_worker.go
  sample/config/executor.toml
  test/e2e/e2e_node_chaos_test.go
  test/e2e/e2e_test_cli.go
Labels: status/ptal

#367 jobmanager(engine): retry on quota error during create worker
  lib/master.go
  servermaster/jobmanager.go
  servermaster/jobmanager_test.go
Labels: status/ptal

#372 executor: Allow MasterNotReady as valid heartbeat response
  executor/server.go
Labels: bug

#375 jobmanager(engine): clean tombstone worker before failover
  servermaster/jobmanager.go
  test/e2e/e2e_node_chaos_test.go
  test/e2e/e2e_test_cli.go
Labels: status/ptal

#374 lib: trigger a masterInfo refresh if the master node is not found
  lib/statusutil/master_info.go
  lib/statusutil/writer.go
  lib/statusutil/writer_test.go
  lib/worker.go
  lib/worker_test.go
Labels: enhancement, status/ptal

#381 lib/master: simplify status update handling
  lib/master/events.go
  lib/master/worker_entry.go
  lib/master/worker_handle.go
  lib/master/worker_manager.go
  lib/statusutil/reader.go
  lib/statusutil/reader_test.go
Labels: status/ptal

#383 externalresource(engine): implement BrokerService
  pb/executor.pb.go
  pkg/externalresource/broker/broker.go
  pkg/externalresource/broker/broker_test.go
  pkg/externalresource/broker/file_manager.go
  pkg/externalresource/broker/interfaces.go
  proto/executor.proto
Labels: status/ptal

#386 fake(engine): worker could be nil in worker list
  lib/fake/fake_master.go
Labels: status/ptal

#384 lint(engine): enable exported comment check for all packages
  .golangci.yml
  executor/worker/internal/info.go
  executor/worker/internal/runnables.go
  jobmaster/dm/checkpoint/agent.go
  jobmaster/dm/checkpoint/agent_test.go
  jobmaster/dm/config/config.go
  jobmaster/dm/dm_jobmaster.go
  jobmaster/dm/metadata/ddl.go
  jobmaster/dm/metadata/job.go
  jobmaster/dm/metadata/state.go
  jobmaster/dm/runtime/worker_status.go
  jobmaster/dm/task_manager.go
  lib/base_jobmaster.go
  lib/common.go
  lib/fake/fake_master.go
  lib/fake/fake_worker.go
  lib/master.go
  lib/master/mock_handle.go
  lib/master/worker_handle.go
  lib/master/worker_manager.go
  lib/message_router.go
  lib/mock_master_impl.go
  lib/mock_master_util.go
  lib/mock_worker_util.go
  lib/model/master.go
  lib/model/messages.go
  lib/registry/factory.go
  lib/registry/globals.go
  lib/registry/register_fake.go
  lib/registry/registry.go
  lib/worker.go
Labels: status/ptal

#388 fake(engine): fix concurrent bug and clean handler on worker offline
  lib/fake/fake_master.go
Labels: status/ptal

#389 externalresource(engine): Adjust resource manager
  pb/executor.pb.go
  pb/resources.pb.go
  pkg/errors/errors.go
  pkg/externalresource/broker/broker.go
  pkg/externalresource/broker/broker_test.go
  pkg/externalresource/broker/local_broker.go
  pkg/externalresource/manager/mock_client.go
  pkg/externalresource/manager/service.go
  pkg/externalresource/manager/service_test.go
  pkg/orm/client.go
  pkg/orm/client_test.go
  proto/executor.proto
  proto/resources.proto
Labels: status/ptal

#391 feat(test): support sqlite as backend DB for unit tests
  go.mod
  go.sum
  lib/model/master.go
  lib/model/status.go
  pkg/externalresource/resourcemeta/model/model.go
  pkg/orm/client.go
  pkg/orm/client_test.go
  pkg/orm/mock.go
  pkg/orm/mock_test.go
Labels: status/ptal

#394 fix(orm): using more proper dsn for sqlite
  pkg/orm/mock.go
  pkg/orm/mock_test.go
Labels: status/ptal

#392 ci(engine): use gh-docker-logs to dump logs in github action
  .github/workflows/dataflow_engine_e2e.yaml
Labels: status/ptal

#361 lib/*(engine): Implement worker exit fast path
  .github/workflows/dataflow_engine_e2e.yaml
  lib/base_jobmaster.go
  lib/fake/fake_master.go
  lib/fake/fake_worker.go
  lib/master.go
  lib/master/worker_entry.go
  lib/master/worker_manager.go
  lib/master/worker_manager_test.go
  lib/model/messages.go
  lib/worker.go
  lib/worker_test.go
  pkg/errors/errors.go
  sample/config/etcd.yml
  test/e2e/e2e_worker_exit_test.go
Labels: status/ptal

#387 Add Multi-projects/tasks prometheus metric support
  go.mod
  go.sum
  lib/model/typedefs.go
  pkg/promutil/factory.go
  pkg/promutil/implement.go
  pkg/promutil/implement_test.go
  pkg/promutil/registry.go
  pkg/promutil/registry_test.go
  pkg/promutil/util.go
  pkg/promutil/util_test.go
  pkg/tenant/tenant.go
Labels: status/ptal

#401 test(promutil): add promutil simulator test
  pkg/promutil/implement.go
  pkg/promutil/implement_test.go
  pkg/promutil/test/Makefile
  pkg/promutil/test/go.mod
  pkg/promutil/test/go.sum
  pkg/promutil/test/multiprojects_metric_scences.go
  pkg/promutil/util.go
  pkg/promutil/util_inner.go
  pkg/promutil/util_inner_test.go
  sample/1prometheus.yaml
  sample/config/alertmanager.yml
  sample/config/prometheus.yml
Labels: status/ptal
